/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Wojciech' at '18.03.17 22:15' with Gradle 3.2
 *
 * @author Wojciech, @date 18.03.17 22:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
